# Generated by Django 5.2.4 on 2025-08-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driver_license_plate_driver_email_driver_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
