# Generated by Django 5.2.5 on 2025-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatches', '0002_alter_dispatch_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
