# Generated by Django 5.2.5 on 2025-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatches', '0003_alter_dispatch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='dispatch_time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
