# Generated by Django 5.2.5 on 2025-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatches', '0004_rename_dispatch_time_dispatch_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='created_at',
            new_name='dispatch_time',
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
